//! Blobby KATs as generated by `gen_blb.rs`

#![allow(missing_docs)]
use cryptobscura::frog::Frog;

cipher::block_cipher_test!(frog_kat_128, "frog_128", Frog);
cipher::block_cipher_test!(frog_kat_192, "frog_192", Frog);
cipher::block_cipher_test!(frog_kat_256, "frog_256", Frog);
